import type { Metadata } from "next";
import localFont from "next/font/local";
import "../scss/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const keplerStd = localFont({ src: "../../public/keplerstd-bold.otf" });
const guru = localFont({ src: "../../public/guru-regular.otf" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${keplerStd.className} ${guru.className}`}>
        {children}
      </body>
    </html>
  );
}
